### ISSUE TITLE
Sample Migration

### ISSUE THREAD

**Issue by rbbl-dev** [pcimcioch/gitlab-ci-kotlin-dsl#2]
Hey there, really like the lib and migrated the CI of one of my Pet Projects to Kotlin with your Lib.

Thought it might be worth adding/referencing it as an [example of sorts.](https://gitlab.com/rbbl/genre-police/-/merge_requests/4?view=inline)

**Comment by pcimcioch** [comment]
I'm glad you found it useful in your project :) I'm happy to add it as an example to the Readme "How to use" section
